move zsmalloc/zram kmods from system_dlkm to vendor_dlkm
because lineage-23.2 kernel build doesn't like that vendor_dlkm kmods
have dependencies in system_dlkm, so build errors out like so:
moto_swap.ko needs unknown symbol zs_malloc
ERROR: kernel module(s) need unknown symbol(s)